[package]
name = "kernel"
version = "0.1.0"
edition = "2024"


[dependencies]
limine = { workspace = true }
x86_64 = { workspace = true }
uart_16550 = "0.4.0"
pic8259 = "0.11.0"
spin = "0.10.0"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
