[build]
target = "i386-unknown-wisp.json"

# Removed to keep the qemu settings in one place
# [target.i386-unknown-wisp]
# runner = "qemu-system-i386 -drive format=raw,file=target/wisp-kern.img,index=0,media=disk"

[unstable]
json-target-spec = true
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
